version: "3.8"

services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017

  doujins:
    build: ./services/doujins/
    volumes:
      - ./services/doujins:/app
    environment:
      - PORT=3000
    depends_on:
      - mongo

  frontend:
    build: ./frontend/
    volumes:
      - ./frontend:/app
    environment:
      - PORT=3000
    depends_on:
      - doujins

  nginx:
    image: nginx:latest
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
    ports:
      - 80:80
